name: YakWeideMinecraftPlugin
version: '${project.version}'
main: de.YakWeide.YakWeideMinecraftPlugin
api-version: 1.18
authors: [ Tim Lisemer, JanReitz ]
description: minecraft plugin
website: Yakweide.de

commands:
  Coords:
  rps:
  accept:
  decline:
  invitationtest:
  cancelGame:
  challengetest: